# Generated by Django 4.0.3 on 2022-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('subcatname', models.CharField(max_length=50, unique=True)),
                ('catname', models.CharField(max_length=50)),
                ('subcaticon', models.CharField(max_length=100)),
            ],
        ),
    ]
