# Generated by Django 4.0.3 on 2022-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('bprice', models.CharField(max_length=50)),
                ('cprice', models.CharField(max_length=50)),
                ('bidprice', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
